controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - base_revolute_joint
      - revolute_upperarm_joint
      - upperarm_forearm_joint
      - forearm_endeffect_joint
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - forearm_endeffect_joint
initial:  # Define initial robot poses per group
  - group: arm
    pose: home