arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.5
  goal_joint_tolerance: 0.001
  goal_position_tolerance: 0.001
  goal_orientation_tolerance: 0.001
  position_only_ik: True
