arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - base_revolute_joint
    - revolute_upperarm_joint
    - upperarm_forearm_joint
    - forearm_endeffect_joint
  gains:
    base_revolute_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    revolute_upperarm_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    upperarm_forearm_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    forearm_endeffect_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - forearm_endeffect_joint
  gains:
    forearm_endeffect_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1